services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    volumes:
      - ../..:/workspaces:cached
    command: sleep infinity
    network_mode: service:storage

  storage:
    image: "mcr.microsoft.com/azure-storage/azurite"
    restart: unless-stopped
    ports:
      - "10000:10000"
      - "10001:10001"
      - "10002:10002"
    volumes:
      - azurite_data:/data

  zipkin:
    image: openzipkin/zipkin
    restart: unless-stopped
    ports:
      - "9411:9411"

volumes:
  azurite_data:
